name: demo-failure-cases

on:
  workflow_dispatch:

jobs:
  build-distribution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build and upload distribution
      uses: ./.github/actions/build-dist

  failing-build:
    needs: build-distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Initialize integ-test
      uses: ./.github/actions/init-integ-test

    - name: Test build failure
      uses: ./setup-gradle
      continue-on-error: true
      with:
        build-root-directory: .github/workflow-samples/kotlin-dsl
        arguments: not-a-valid-task

  wrapper-missing:
    needs: build-distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Initialize integ-test
      uses: ./.github/actions/init-integ-test

    - name: Test wrapper missing
      uses: ./setup-gradle
      continue-on-error: true
      with:
        build-root-directory: .github/workflow-samples/no-wrapper
        arguments: help

  bad-configuration:
    needs: build-distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Initialize integ-test
      uses: ./.github/actions/init-integ-test

    - name: Test bad config value
      uses: ./setup-gradle
      continue-on-error: true
      with:
        build-root-directory: .github/workflow-samples/no-wrapper
        arguments: help
        cache-disabled: yes
